version: "3.9"

services:
  mysql_sqli:
    image: mysql:8.0
    container_name: mysql_sqli
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - shared-data:/shared
    command: --secure-file-priv=""
    ports:
      - "3307:3306"

  flask_sqli:
    build: .
    container_name: flask_sqli
    depends_on:
      - mysql_sqli
    volumes:
      - shared-data:/shared
    ports:
      - "5005:5005"

volumes:
  shared-data:
