version: "3.8"

services:

  db:
    image: mysql:8.0
    container_name: mysql_sqli
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqli
    ports:
      - "3306:3306"
    command: --secure-file-priv=""
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - dbdata:/var/lib/mysql

  web:
    build: .
    container_name: flask_sqli
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: sqli
    ports:
      - "5004:5004"
   
volumes:
  dbdata:
